<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<qualifiedTypeNameHistroy>
<fullyQualifiedTypeName name="InnerClass.Inner"/>
<fullyQualifiedTypeName name="java.util.ArrayList"/>
<fullyQualifiedTypeName name="java.util.ListIterator"/>
<fullyQualifiedTypeName name="Exception2"/>
<fullyQualifiedTypeName name="SuperException"/>
<fullyQualifiedTypeName name="SubException"/>
<fullyQualifiedTypeName name="java.io.FileNotFoundException"/>
<fullyQualifiedTypeName name="java.lang.ArrayIndexOutOfBoundsException"/>
<fullyQualifiedTypeName name="java.io.IOException"/>
<fullyQualifiedTypeName name="java.sql.SQLException"/>
<fullyQualifiedTypeName name="java.lang.RuntimeException"/>
<fullyQualifiedTypeName name="Sample5"/>
<fullyQualifiedTypeName name="java.lang.NullPointerException"/>
<fullyQualifiedTypeName name="java.lang.ArithmeticException"/>
<fullyQualifiedTypeName name="java.lang.Throwable"/>
<fullyQualifiedTypeName name="java.lang.Exception"/>
</qualifiedTypeNameHistroy>
